name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  automerge_dependabot:
    permissions:
      pull-requests: write
      contents: write
    uses: "philipcristiano/workflows/.github/workflows/automerge_dependabot.yml@main"
    with:
      automerge: true

  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
